name: CI

on:
  push:
    branches: [main]
    paths:
      - "api/**"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "api/**"
      - ".github/workflows/ci.yml"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    outputs:
      jar: ${{ steps.build.outputs.jar }}

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "21"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build and test
        id: build
        run: ./gradlew build -x jar

      - name: Updload jar
        uses: actions/upload-artifact@v7
        with:
          name: jar
          path: api/build/libs/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download jar
        uses: actions/download-artifact@v7
        with:
          name: jar

      - name: Print Jar file
        run: ls -l
