name: CI

on:
  push:
    branches: [main]
    paths:
      - "api/**"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "api/**"
      - ".github/workflows/ci.yml"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    outputs:
      jar_name: ${{ steps.extract-jar.outputs.jar_name }}

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "21"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build and test
        id: build
        run: ./gradlew build -x jar

      - name: Extract jar
        id: extract-jar
        run: |
          JAR_NAME=$(basename $(find build/libs -type f))
          echo "jar_name=$JAR_NAME" >> $GITHUB_OUTPUT

      - name: Upload jar
        uses: actions/upload-artifact@v7
        with:
          name: jar
          path: build/libs/$JAR_NAME

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download jar
        uses: actions/download-artifact@v7
        with:
          name: jar

      - name: Renomeia jar
        run: mv ${{ needs.build.outputs.jar_name }} salesbook.jar

      - name: Enviar o .jar para o EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "salesbook.jar"
          target: "/home/${{ secrets.EC2_USERNAME }}/app/"

      - name: Reiniciar o serviço systemd via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Reinicia o serviço
            sudo systemctl restart salesbook.service
            # Verifica o status
            sudo systemctl status salesbook.service
